name: Noah's Ark
markdown: kramdown
highlighter: pygments
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: America/Montreal

permalink: /blog/:categories/:year/:month/:day/:title.html
paginate_path: /blog/page:num

prose:
  rooturl: '_posts'
  siteurl: 'http://www.noahsarkmusic.com'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
