name: Noah's Ark
markdown: kramdown
highlighter: pygments
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: America/Montreal
url: http://www.noahsarkmusic.com

permalink: /blog/:categories/:year/:month/:day/:title.html
paginate_path: /blog/page:num
paginate: 5

gems:
  - jekyll-sitemap
