name: Noah's Ark Music
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: America/Montreal
url: http://www.noahsarkmusic.com

permalink: /blog/:categories/:year/:month/:day/:title.html
paginate_path: /blog/page:num
paginate: 5

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
